print ("Welcome to Prabhu's Pizza Corner")
print ("Tell us how we can make your pizza perfect!")
size = input("What size pizza do you want? S, M or L: ")
pepperoni = input("Do you want pepperoni on your pizza? Y or N: ")
extra_cheese = input("Do you want extra cheese? Y or N: ")